### ISSUE TITLE
Can we use Python 3.8 for nox?

### ISSUE THREAD

**Issue by devos50** [grimadas/noodle#27]
Currently, Python 3.7 is specified as interpreter version in `noxfile.py`. However, I don't have Python 3.7 installed on my Mac, nor do I want to install an older Python version (I have 3.8, installed with Brew). Can we either use Python 3.8 with Nox, or specify that Nox always uses the latest Python version installed on the system?

**Comment by grimadas** [comment]
I think yes, we need to migrate to 3.8v. Last time I checked there were problems with some of the deps, but I think it is resolved now.
