### ISSUE TITLE
The set_vals method is implemented five times in the tests

### ISSUE THREAD

**Issue by devos50** [grimadas/noodle#45]
The `set_vals` method that is responsible for initialising an overlay in the tests is implemented five times. All these implementations are very similar. We can save a lot of code if we can just implement this method twice.

**Comment by Solomon1732** [comment]
Where should the logic be moved to? On the surface it looks simple enough: just move the logic and update the references accordingly. I don't mind trying to tackle this issue.

**Comment by devos50** [comment]
It should move to a common class, and probably be parameterized accordingly. As a first step though, I suggest to setup your local dev environment and get the unit tests up and running. This project is using a few libraries that helps us with QA/testing 👍
