### ISSUE TITLE
Warning of coroutine never awaited on tests

### ISSUE THREAD

**Issue by Solomon1732** [grimadas/noodle#52]
When running the tests on the latest repo this is the warning I got:
```
=============================== warnings summary ===============================
tests/payment/test_community.py::TestMint::test_invalid_mint_tx_value_out_of_range[20]
  /home/user/.cache/pypoetry/virtualenvs/bami-O6MDcsrF-py3.8/lib64/python3.8/site-packages/ipv8/messaging/serialization.py:166: RuntimeWarning: coroutine 'interval_runner' was never awaited
    return super(DefaultStruct, self).pack(*data), self.size

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

So far I have not changed any files in the local repository. This is after installing the project's dependencies.

Edit: This was done after being recommended in #45 to set up the dev environment in order to deal with the linked issue

**Comment by devos50** [comment]
Thanks for reporting! This error is non-critical and originates from IPv8. In fact, I have seen it several times in the Tribler/IPv8 unit tests 👍
